### ISSUE TITLE
Improve comparisons

### ISSUE THREAD

**Issue by oesgalha** [instruct-br/puppet_auditor#1]
Right now this tool is naive and only make comparison against direct assignment to resource attributes.

With the following set of rules:
```yaml
puppet_auditor_version: '1'
rules:
- name: Cant open low ports
  resource: firewall
  attributes:
    dport:
      less_than: 1024
  message: Should not open port below 1024
```
The following code will receive a warning:
```puppet
firewall { 'allow 22 access':
  dport  => 22,
  proto  => tcp,
  action => accept,
}
```

But this one will not:
```puppet
$port = 22

firewall { 'allow 22 access':
  dport  => $port,
  proto  => tcp,
  action => accept,
}
```

There are some other cases where it's possible to discover the value being assigned to the resource.

This issue is a ticket to implement the following cases:
- [x] values returned by hiera/lookup functions when the value is inside the repo
- [x] default values from class parameters
- [x] values from variables assigned inside the same file

It will be possible to avoid the tool auditing capacity even with those rules implemented, but this improvement should cover a good range of use cases.

**Comment by oesgalha** [comment]
WIP at ` variable_assignment ` branch.

Implemented variables with scopes and interpolation.

This set of rules:
```yaml
puppet_auditor_version: '1'
rules:
- name: Check Gerenciamento
  resource: file
  attributes:
    content:
      equals: GTSL
  message: GTSL is not a valid value for gerenciamento anymore
```

Detects violation in the following code:
```puppet
$gerenciamento = 'GT'

node 'acme.dev' {
  $gerenciamento = 'GTS'

  class gerenciamento {
    $gerenciamento = "GTSL"
    
    file { '/etc/facts.d/gerenciamento.txt':
      ensure => file,
      content => "${gerenciamento}",
    }
  }
}
```

And in the following code:
```puppet
node 'acme.dev' {  
  class gerenciamento {
    $gerenciamento = "GTSL"
    
    file { '/etc/facts.d/gerenciamento.txt':
      ensure => file,
      content => $gerenciamento,
    }
  }
  $gerenciamento = 'GTS'
}
$gerenciamento = 'GT'
```

**Comment by oesgalha** [comment]
Implemented support for class default parameter values.

This set of rules:
```yaml
puppet_auditor_version: '1'
rules:
- name: Firewall low ports
    resource: firewall
    attributes:
    dport:
        less_than: 1024
    message: Should not open port below 1024
```

Detects violation in the following code:
```puppet
class sshconfig(
  Integer $port = 22,
) {
  firewall { 'allow 22 access':
    dport  => $port,
    proto  => tcp,
    action => accept,
  }
}
```

**Comment by oesgalha** [comment]
Implemented suport for hiera/lookup functions.

This set of rules:
```yaml
puppet_auditor_version: '1'
rules:
- name: use a package version
  resource: package
  attributes:
    ensure:
      equals: installed
  message: Please specify a package version
```

And a module with an unusual hiera yaml:
```yaml
puppetserver::version_key: 'puppetserver::version'
i: 'i'
n: 'n'
s: 's'
t: 't'
a: 'a'
l: 'l'
l: 'l'
e: 'e'
d: 'd'
puppetserver::version: "%{hiera('i')}%{hiera('n')}%{hiera('s')}%{hiera('t')}%{hiera('a')}%{hiera('l')}%{hiera('l')}%{hiera('e')}%{hiera('d')}"
```

The tool detects violation in the following code:
```puppet
  package { 'puppetserver':
    ensure => hiera(hiera('puppetserver::version_key')),
  }
```
